insert into public.prompts (
  slug,
  title,
  category,
  difficulty_tier,
  scenario_context,
  prompt_text,
  target_duration_sec,
  target_word_range_min,
  target_word_range_max,
  pillar_weights,
  behavior_targets
)
values
  (
    'baseline-bluf',
    'Status update with BLUF',
    'bluf_structured_thinking',
    1,
    'Your CEO asks for a quick update on a delayed launch.',
    'Give a 45-second update with the answer first, then the three most important points, then the ask.',
    45,
    70,
    105,
    jsonb_build_object('clarity', 0.4, 'structure', 0.4, 'brevity', 0.2),
    jsonb_build_object('direct_answer_rate', 0.8, 'bluf_usage_rate', 0.8)
  ),
  (
    'baseline-direct',
    'Direct answer discipline',
    'direct_answer_discipline',
    1,
    'A VP asks whether the team should pause a feature launch.',
    'Answer yes or no immediately, give your recommendation, and explain only the most important reasoning.',
    35,
    45,
    80,
    jsonb_build_object('clarity', 0.5, 'brevity', 0.3, 'structure', 0.2),
    jsonb_build_object('direct_answer_rate', 0.9, 'response_length_words', 70)
  ),
  (
    'baseline-brevity',
    'Compression under constraint',
    'brevity_compression',
    1,
    'You have 30 seconds at the end of a leadership meeting.',
    'Summarize the update in under 30 seconds without losing the key recommendation.',
    30,
    35,
    55,
    jsonb_build_object('brevity', 0.5, 'clarity', 0.3, 'structure', 0.2),
    jsonb_build_object('response_length_words', 50, 'bluf_usage_rate', 0.7)
  ),
  (
    'baseline-presence',
    'Executive presence',
    'executive_presence',
    1,
    'A senior leader pushes back on your proposal in a meeting.',
    'Respond calmly, keep ownership, and restate the recommendation with confident economy.',
    45,
    55,
    90,
    jsonb_build_object('presence', 0.45, 'clarity', 0.3, 'brevity', 0.25),
    jsonb_build_object('filler_words_per_minute', 4, 'direct_answer_rate', 0.75)
  ),
  (
    'baseline-pressure',
    'Pressure response',
    'pressure_response',
    2,
    'A production outage affects a top-tier customer.',
    'Deliver the immediate response plan, risk framing, and next update cadence.',
    50,
    65,
    100,
    jsonb_build_object('pressure_response', 0.45, 'structure', 0.3, 'clarity', 0.25),
    jsonb_build_object('direct_answer_rate', 0.8, 'clean_three_point_structure_rate', 0.7)
  ),
  (
    'baseline-strategy',
    'Strategic framing',
    'strategic_framing',
    2,
    'The company must choose between two expansion bets.',
    'Recommend one option, explain the tradeoff, and tie it to business impact.',
    60,
    80,
    120,
    jsonb_build_object('strategic_framing', 0.45, 'clarity', 0.25, 'structure', 0.3),
    jsonb_build_object('bluf_usage_rate', 0.8, 'direct_answer_rate', 0.8)
  ),
  (
    'baseline-summary',
    'Listening and summarization',
    'listening_summarization',
    1,
    'A customer call ends with multiple asks and one hidden risk.',
    'Summarize the call in a crisp executive readout with decisions, risks, and next steps.',
    50,
    65,
    95,
    jsonb_build_object('clarity', 0.4, 'structure', 0.4, 'brevity', 0.2),
    jsonb_build_object('clean_three_point_structure_rate', 0.8, 'direct_answer_rate', 0.75)
  ),
  (
    'plan-1',
    'Recommendation with three reasons',
    'direct_answer_discipline',
    1,
    'A leader asks whether to prioritize speed or polish.',
    'Give the recommendation immediately and support it with three short reasons.',
    40,
    55,
    85,
    jsonb_build_object('clarity', 0.45, 'structure', 0.3, 'brevity', 0.25),
    jsonb_build_object('direct_answer_rate', 0.85)
  ),
  (
    'plan-2',
    'Condense the update',
    'brevity_compression',
    1,
    'You get one minute in a staff meeting.',
    'Compress the update into headline, risk, and ask.',
    30,
    35,
    55,
    jsonb_build_object('brevity', 0.45, 'clarity', 0.35, 'structure', 0.2),
    jsonb_build_object('response_length_words', 50)
  ),
  (
    'plan-3',
    'Executive pushback',
    'executive_presence',
    2,
    'An executive challenges your numbers in front of the room.',
    'Respond with calm ownership, keep the answer short, and offer the next step.',
    45,
    55,
    85,
    jsonb_build_object('presence', 0.45, 'clarity', 0.3, 'structure', 0.25),
    jsonb_build_object('filler_words_per_minute', 4)
  ),
  (
    'plan-4',
    'Incident escalation',
    'pressure_response',
    2,
    'A vendor failure may impact revenue this quarter.',
    'Give the escalation summary, immediate action, and executive ask.',
    50,
    65,
    100,
    jsonb_build_object('pressure_response', 0.45, 'structure', 0.3, 'clarity', 0.25),
    jsonb_build_object('direct_answer_rate', 0.8)
  ),
  (
    'plan-5',
    'Strategic recommendation memo',
    'strategic_framing',
    3,
    'Leadership is split between growth and margin.',
    'Recommend one path, name the tradeoff, and tie it to business impact.',
    60,
    85,
    120,
    jsonb_build_object('strategic_framing', 0.5, 'clarity', 0.2, 'structure', 0.3),
    jsonb_build_object('bluf_usage_rate', 0.8)
  ),
  (
    'plan-6',
    'Meeting summary for a VP',
    'listening_summarization',
    2,
    'A long cross-functional meeting ended with unclear ownership.',
    'Summarize what matters, what changed, and who owns the next move.',
    45,
    55,
    90,
    jsonb_build_object('clarity', 0.35, 'structure', 0.45, 'brevity', 0.2),
    jsonb_build_object('clean_three_point_structure_rate', 0.8)
  ),
  (
    'plan-7',
    'BLUF with escalation',
    'bluf_structured_thinking',
    2,
    'A key dependency slipped and leadership needs the headline fast.',
    'Deliver a bottom-line-up-front update with the problem, impact, and ask.',
    40,
    55,
    85,
    jsonb_build_object('clarity', 0.4, 'structure', 0.4, 'brevity', 0.2),
    jsonb_build_object('bluf_usage_rate', 0.85)
  ),
  (
    'plan-8',
    'Answer under ambiguity',
    'direct_answer_discipline',
    3,
    'The data is incomplete but leadership still wants a recommendation.',
    'Give your recommendation, note the uncertainty, and propose the safest next move.',
    50,
    60,
    95,
    jsonb_build_object('clarity', 0.45, 'structure', 0.25, 'pressure_response', 0.3),
    jsonb_build_object('direct_answer_rate', 0.85)
  )
on conflict (slug) do update
set
  title = excluded.title,
  category = excluded.category,
  difficulty_tier = excluded.difficulty_tier,
  scenario_context = excluded.scenario_context,
  prompt_text = excluded.prompt_text,
  target_duration_sec = excluded.target_duration_sec,
  target_word_range_min = excluded.target_word_range_min,
  target_word_range_max = excluded.target_word_range_max,
  pillar_weights = excluded.pillar_weights,
  behavior_targets = excluded.behavior_targets,
  is_active = true;
